### PR TITLE
Don't unhook BXT modules in the FreeLibrary hook

### PR DESCRIPTION
**Pull request by hobokenn**

### CODE REVIEW

**Comment by YaLTeR** [comment]
Corresponding BXT PR: https://github.com/YaLTeR/BunnymodXT/pull/370/files

@lipsanen and idk who else, is this kind of change ok?

**Comment by SirWillian** [comment]
Couldn't it be made optional to unhook in FreeLibrary? Probably still makes sense in plenty of cases to allow this to happen

**Comment by lipsanen** [comment]
Dont think this should be an issue. Main concerns would be the unloading/restart code, but in those everything should get unhooked before the restart/unload takes place so I think it's fine.

**Comment by YaLTeR** [comment]
Alright, let's merge this I guess.

**Pull request merged**
